# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:5.0.15
    container_name: workout-app-local-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - workout-app-local-mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    # networks:
    #   - backend

  mongo-express:
    image: mongo-express
    container_name: workout-app-local-mongodb-admin-web-tool
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
    # networks:
    #   - backend

volumes:
  workout-app-local-mongodb-data:
    name: "workout-app-local-mongodb-volume"

# networks:
#   backend:
#     name: workoutapp-backend-network
